export interface Env {
  DB: D1Database;
  LICENSE_KEY_PEPPER?: string;
  LICENSE_SIGNING_PRIVATE_KEY?: string;
  LICENSE_SIGNING_PUBLIC_KEY_V1?: string;
  LICENSE_TRUSTED_PUBLIC_KEYS_JSON?: string;
  LICENSE_ADMIN_TOKEN?: string;
  LICENSE_SIGNING_KEY_ID: string;
  APP_PACKAGE_NAME: string;
  ANDROID_ALLOWED_SIGNING_CERT_SHA256?: string;
  ACTIVATION_LIMITER?: RateLimit;
  PUBLIC_IP_LIMITER?: RateLimit;
  REFRESH_LIMITER?: RateLimit;
  ADMIN_AUTH_LIMITER?: RateLimit;
  ADMIN_UNAUTH_LIMITER?: RateLimit;
}
