export const PORTAL_HTML = `<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>DexWorkspaceTouch Operator</title><style>
:root{font-family:system-ui,sans-serif;color:#172033;background:#f4f6fb}*{box-sizing:border-box}body{margin:0}header{position:sticky;top:0;background:#172c4d;color:white;padding:18px 16px;z-index:2}header h1{font-size:20px;margin:0}.wrap{max-width:720px;margin:auto;padding:16px}section,.card{background:white;border-radius:16px;padding:16px;margin-bottom:14px;box-shadow:0 2px 12px #17203314}h2{font-size:18px;margin:0 0 14px}label{display:block;font-weight:650;margin:12px 0 6px}input,button{font:inherit;min-height:48px;border-radius:12px;border:1px solid #aab4c5;padding:10px 12px;width:100%}button{background:#174d87;color:white;border:0;font-weight:700;margin-top:10px}button.secondary{background:#e8eef7;color:#17375e}button.danger{background:#a12828}button:disabled{opacity:.5}.row{display:flex;gap:10px}.row>*{flex:1}.status{display:inline-block;border-radius:999px;background:#e8eef7;padding:5px 9px;font-size:12px;font-weight:700}.muted{color:#5c6878;font-size:14px}.key{font-family:monospace;font-size:18px;overflow-wrap:anywhere;background:#fff5cc;padding:14px;border-radius:10px}.hidden{display:none}.error{background:#ffe4e4;color:#7c1717;padding:12px;border-radius:10px;margin-bottom:12px}#toast{position:fixed;bottom:18px;left:16px;right:16px;max-width:688px;margin:auto;background:#152238;color:#fff;padding:14px;border-radius:12px;display:none;z-index:4}
</style></head><body><header><h1>DexWorkspaceTouch Operator</h1></header><main class="wrap">
<div id="error" class="error hidden"></div>
<section><h2>+ Tạo license</h2><form id="create"><label>Mã đơn hàng *</label><input name="orderReference" required maxlength="100" autocomplete="off"><label>Mã khách hàng</label><input name="customerReference" maxlength="100" autocomplete="off"><div class="row"><div><label>Số thiết bị</label><input name="maxDevices" type="number" min="1" max="100" value="1"></div><div><label>Hết hạn</label><input name="expiresAt" type="datetime-local"></div></div><button>Tạo license</button></form></section>
<section id="oneTime" class="hidden"><h2>License Key — chỉ hiển thị lần này</h2><p id="newKey" class="key"></p><div class="row"><button id="copyKey">Sao chép Key</button><button id="copyDelivery">Sao chép thông tin</button></div><div class="row"><button id="download" class="secondary">Tải customer-delivery.txt</button><button id="share" class="secondary">Chia sẻ</button></div><button id="delivered">Đã giao</button><p class="muted">Reload sẽ làm mất key. Portal không thể khôi phục key cũ.</p></section>
<section><h2>Tìm đơn hàng</h2><form id="search" class="row"><input name="query" placeholder="Order, fulfillment, license, customer"><button style="max-width:110px">Tìm</button></form></section>
<section><h2>Recent fulfillments</h2><div id="list"><p class="muted">Đang tải…</p></div></section>
<section id="detail" class="hidden"><h2>Chi tiết</h2><div id="detailBody"></div><div class="row"><button id="detailDelivered" class="secondary">Đã giao</button><button id="revoke" class="danger">Thu hồi</button></div><form id="replace"><label>Mã đơn thay thế *</label><input name="orderReference" required maxlength="100"><label>Mã khách hàng</label><input name="customerReference" maxlength="100"><button class="danger">Thay license</button></form></section>
</main><div id="toast"></div><script nonce="__SCRIPT_NONCE__">
const $=id=>document.getElementById(id),state={one:null,current:null};
async function api(path,options={}){const response=await fetch(path,{...options,headers:{...(options.body?{'Content-Type':'application/json','X-DWT-CSRF':'1'}:{}),...(options.headers||{})}});const body=await response.json();if(!response.ok)throw new Error(body.error?.message||'Operation failed');return body}
function error(value){$('error').textContent=value;$('error').classList.toggle('hidden',!value)}function toast(value){$('toast').textContent=value;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2200)}
function line(parent,label,value){const p=document.createElement('p');const b=document.createElement('b');b.textContent=label+': ';p.append(b,document.createTextNode(value??'—'));parent.append(p)}
async function load(query=''){error('');const data=await api('/api/fulfillments?query='+encodeURIComponent(query));const list=$('list');list.replaceChildren();if(!data.fulfillments.length){list.append(Object.assign(document.createElement('p'),{textContent:'Chưa có fulfillment.'}));return}data.fulfillments.forEach(item=>{const card=document.createElement('button');card.className='card secondary';card.style.textAlign='left';card.append(Object.assign(document.createElement('b'),{textContent:item.orderReference}),document.createElement('br'),Object.assign(document.createElement('span'),{className:'status',textContent:item.status}),document.createElement('br'),Object.assign(document.createElement('small'),{textContent:item.licenseId+' · '+new Date(item.createdAt).toLocaleString()}));card.onclick=()=>show(item.fulfillmentId);list.append(card)})}
async function show(id){const data=await api('/api/fulfillments/'+encodeURIComponent(id));state.current=data.record;const body=$('detailBody');body.replaceChildren();line(body,'Order',data.record.orderReference);line(body,'Customer',data.record.customerReference);line(body,'License ID',data.record.licenseId);line(body,'Trạng thái',data.record.status);line(body,'Bản giao ban đầu',data.record.initialReleaseVersion+' ('+data.record.initialReleaseVersionCode+')');line(body,'APK SHA-256',data.record.apkSha256);const notice=document.createElement('p');notice.className='muted';notice.textContent='License Key is no longer available. Use replacement workflow if the key was not delivered.';body.append(notice);const devices=document.createElement('div');line(devices,'Thiết bị',String(data.devices.length));data.devices.forEach(device=>{const button=document.createElement('button');button.className='secondary';button.textContent=(device.deviceId||'device')+' · '+(device.status||'unknown')+' — Reset';button.onclick=async()=>{if(confirm('Reset thiết bị này?')){await mutate('/api/fulfillments/'+encodeURIComponent(id)+'/devices/'+encodeURIComponent(device.deviceId)+'/reset',{});await show(id)}};devices.append(button)});body.append(devices);const history=document.createElement('div');line(history,'Audit events',String(data.events.length));data.events.forEach(event=>line(history,event.eventType,new Date(event.occurredAt).toLocaleString()+' · '+event.operatorIdentity));body.append(history);$('detail').classList.remove('hidden');$('detail').scrollIntoView({behavior:'smooth'})}
async function mutate(path,body){return api(path,{method:'POST',body:JSON.stringify(body)})}
$('create').onsubmit=async e=>{e.preventDefault();error('');const f=new FormData(e.target),expiry=f.get('expiresAt');try{const result=await mutate('/api/fulfillments',{orderReference:f.get('orderReference'),customerReference:f.get('customerReference')||null,maxDevices:Number(f.get('maxDevices')),expiresAtEpochSeconds:expiry?Math.floor(new Date(expiry).getTime()/1000):null});state.one=result;$('newKey').textContent=result.licenseKey;$('oneTime').classList.remove('hidden');await load();$('oneTime').scrollIntoView({behavior:'smooth'})}catch(e){error(e.message)}};
$('search').onsubmit=e=>{e.preventDefault();load(new FormData(e.target).get('query')).catch(e=>error(e.message))};
$('copyKey').onclick=()=>navigator.clipboard.writeText(state.one?.licenseKey||'').then(()=>toast('Đã sao chép Key'));
$('copyDelivery').onclick=()=>navigator.clipboard.writeText(state.one?.deliveryText||'').then(()=>toast('Đã sao chép thông tin'));
$('download').onclick=()=>{if(!state.one)return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([state.one.deliveryText],{type:'text/plain;charset=utf-8'}));a.download='customer-delivery.txt';a.click();URL.revokeObjectURL(a.href)};
$('share').onclick=async()=>{if(!state.one)return;if(navigator.share)await navigator.share({title:'DexWorkspaceTouch',text:state.one.deliveryText});else await navigator.clipboard.writeText(state.one.deliveryText);toast(navigator.share?'Đã mở chia sẻ':'Đã sao chép')};
$('delivered').onclick=async()=>{if(!state.one)return;await mutate('/api/fulfillments/'+encodeURIComponent(state.one.record.fulfillmentId)+'/delivered',{});state.one=null;$('newKey').textContent='';$('oneTime').classList.add('hidden');toast('Đã ghi nhận giao khách');await load()};
$('detailDelivered').onclick=async()=>{if(state.current){await mutate('/api/fulfillments/'+encodeURIComponent(state.current.fulfillmentId)+'/delivered',{});await show(state.current.fulfillmentId);await load()}};
$('revoke').onclick=async()=>{if(state.current&&confirm('Thu hồi license '+state.current.orderReference+'?')){await mutate('/api/fulfillments/'+encodeURIComponent(state.current.fulfillmentId)+'/revoke',{cancelled:false});await show(state.current.fulfillmentId);await load()}};
$('replace').onsubmit=async e=>{e.preventDefault();if(!state.current||!confirm('Thu hồi license cũ và tạo license thay thế?'))return;const f=new FormData(e.target);try{const result=await mutate('/api/fulfillments/'+encodeURIComponent(state.current.fulfillmentId)+'/replace',{orderReference:f.get('orderReference'),customerReference:f.get('customerReference')||null,maxDevices:state.current.maxDevices,expiresAtEpochSeconds:state.current.expiresAt});state.one=result;$('newKey').textContent=result.licenseKey;$('oneTime').classList.remove('hidden');$('oneTime').scrollIntoView({behavior:'smooth'});await load()}catch(e){error(e.message)}};
load().catch(e=>error(e.message));
</script></body></html>`;
